language: python
python:
- '3.5'
install:
- pip install nose
- pip install -r requirements.txt
script: nosetests -s --verbosity=3
deploy:
  provider: pypi
  user: mainro
  password:
    secure: eJMV8WJj053Tr08lWPg9cEjoDfU4xF0qgPXDPMlnjl2QPvGmt2VGXGWT0E8q3DBWd0gIEIY8NNkW4Px6nrXfSPPYM4yNZx5SXGdnv3SeNQ2rySshXW+Il6u8vF7jh8Am/OofnJZs7oBou/+ssXVgQ1Tc1OY3VRZnYCl7cIIwR2tEasDfr2h26R/EENb/ct6ODBG/o84SEMf2XSaGWg0W1RtChJWWYJ/xjmjoH1E9b8CxBgoyJ4E+7opL7jc9g4P3b06B/w49okWBhoPzrOza5AwqKlVdrbgs8bxL0AEN0uU3bTGSqWqWWfo8EA04sgYoSqkj8RXyMcUu+ZsXf5UMQMvbpMXl1TviARJx1QXPqPTJjXnrHcOZr/W0+1cd2hYuIDIZ3hsk8x8KKg7bwHz7rQXrmf+XJq+XrfewqrIet3GXytyTOTQ0heUkc2Ajp7dH8VLo87ox9bgmAe4jK4g7WsDweW2UUVtxcGYs33a/WdcKq9EyUCoawKKmy7oMvq8YAmq+k+PWpbk92BczVoueDsvDD4cKKw8NPPOqK1eS2muHOPrDbFFPR1v920QmSx3sC2s3SuuWW6szY+liDg4/bnaC7K7IP9UGEJWWJLqVb/4sgbh5bLTlGK9uPxz6bBM5qi9jDprCf6vykxGi4Q6tv5mW7BMey1iR0aGpAGmLvNI=
  on:
    tags: true
